
# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

# whitelist
branches:
  only:
    - master
    - TravisTesting

language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
install:
- chmod +x Scripts
- ./Scripts/install.sh