
# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

# whitelist
branches:
  only:
    - master
    - dev

language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
before-install:
- chmod +x Scripts
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh